import type { NextPage } from 'next'
import Head from 'next/head'
import Body from './Body'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Body />

      <footer className={styles.footer}>
        <a
          href="https://github.com/dyefim"
          target="_blank"
          rel="noopener noreferrer"
        >
          My github: https://github.com/dyefim
        </a>
      </footer>
    </div>
  )
}

export default Home
