import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Checkbox } from '@chakra-ui/react'

const Home: NextPage = () => {
  const [isChecked, setIsChecked] = useState(true)
  const handleCheckboxChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setIsChecked(event.target.checked)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Project X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Checkbox checked={isChecked} onChange={handleCheckboxChange}>
          {isChecked ? 'Un' : 'C'}heck me
        </Checkbox>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/dyefim"
          target="_blank"
          rel="noopener noreferrer"
        >
          My github: https://github.com/dyefim
        </a>
      </footer>
    </div>
  )
}

export default Home
